---
--- Demo data for SchemaNest to test and showcase it
---
INSERT INTO json_schema (id, identifier)
VALUES (1, 'product_schema'),
       (2, 'user_profile_schema'),
       (3, 'order_event_schema'),
       (4, 'payment_transaction_schema'),
       (5, 'event_log_schema'),
       (6, 'customer_feedback_schema'),
       (7, 'device_telemetry_schema'),
       (8, 'inventory_item_schema');

INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (1, 2, 14, 0,
        '{"type": "object", "properties": {"product_id": {"type": "string", "format": "uuid"}, "name": {"type": "string", "minLength": 3, "maxLength": 200}, "description": {"type": "string", "maxLength": 1000}, "price": {"type": "number", "minimum": 0, "exclusiveMinimum": 0}, "currency": {"type": "string", "pattern": "^[A-Z]{3}$"}, "category": {"type": "string", "enum": ["Electronics", "Books", "Clothing", "Home & Kitchen", "Sports", "Beauty", "Automotive"]}, "stock_quantity": {"type": "integer", "minimum": 0}, "is_available": {"type": "boolean"}, "specifications": {"type": "object", "properties": {"weight_kg": {"type": "number"}, "dimensions_cm": {"type": "string"}, "color": {"type": "string"}}}, "tags": {"type": "array", "items": {"type": "string"}, "uniqueItems": true, "maxItems": 10}, "brand": {"type": "string"}, "created_at": {"type": "string", "format": "date-time"}, "updated_at": {"type": "string", "format": "date-time"}, "avg_rating": {"type": "number", "minimum": 1, "maximum": 5}, "reviews_count": {"type": "integer", "minimum": 0}, "materials": {"type": "array", "items": {"type": "string"}, "uniqueItems": true}}, "required": ["product_id", "name", "price", "currency", "category", "stock_quantity", "is_available"]}',
        'Minor update: Added "materials" array to product schema.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (1, 2, 14, 1,
        '{"type": "object", "properties": {"product_id": {"type": "string", "format": "uuid"}, "name": {"type": "string", "minLength": 3, "maxLength": 200}, "description": {"type": "string", "maxLength": 1000}, "price": {"type": "number", "minimum": 0, "exclusiveMinimum": 0}, "currency": {"type": "string", "pattern": "^[A-Z]{3}$"}, "category": {"type": "string", "enum": ["Electronics", "Books", "Clothing", "Home & Kitchen", "Sports", "Beauty", "Automotive"]}, "stock_quantity": {"type": "integer", "minimum": 0}, "is_available": {"type": "boolean"}, "specifications": {"type": "object", "properties": {"weight_kg": {"type": "number"}, "dimensions_cm": {"type": "string"}, "color": {"type": "string"}}}, "tags": {"type": "array", "items": {"type": "string"}, "uniqueItems": true, "maxItems": 10}, "brand": {"type": "string"}, "created_at": {"type": "string", "format": "date-time"}, "updated_at": {"type": "string", "format": "date-time"}, "avg_rating": {"type": "number", "minimum": 1, "maximum": 5}, "reviews_count": {"type": "integer", "minimum": 0}, "materials": {"type": "array", "items": {"type": "string", "enum": ["Cotton", "Polyester", "Metal", "Plastic", "Wood", "Glass"]}, "uniqueItems": true}}, "required": ["product_id", "name", "price", "currency", "category", "stock_quantity", "is_available"]}',
        'Patch: Added enum for "materials" array items.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (1, 2, 15, 0,
        '{"type": "object", "properties": {"product_id": {"type": "string", "format": "uuid"}, "name": {"type": "string", "minLength": 3, "maxLength": 200}, "description": {"type": "string", "maxLength": 1000}, "price": {"type": "number", "minimum": 0, "exclusiveMinimum": 0}, "currency": {"type": "string", "pattern": "^[A-Z]{3}$"}, "category": {"type": "string", "enum": ["Electronics", "Books", "Clothing", "Home & Kitchen", "Sports", "Beauty", "Automotive"]}, "stock_quantity": {"type": "integer", "minimum": 0}, "is_available": {"type": "boolean"}, "specifications": {"type": "object", "properties": {"weight_kg": {"type": "number"}, "dimensions_cm": {"type": "string"}, "color": {"type": "string"}}}, "tags": {"type": "array", "items": {"type": "string"}, "uniqueItems": true, "maxItems": 10}, "brand": {"type": "string"}, "created_at": {"type": "string", "format": "date-time"}, "updated_at": {"type": "string", "format": "date-time"}, "avg_rating": {"type": "number", "minimum": 1, "maximum": 5}, "reviews_count": {"type": "integer", "minimum": 0}, "materials": {"type": "array", "items": {"type": "string", "enum": ["Cotton", "Polyester", "Metal", "Plastic", "Wood", "Glass"]}, "uniqueItems": true}, "image_urls": {"type": "array", "items": {"type": "string", "format": "uri"}, "minItems": 1, "maxItems": 5}}, "required": ["product_id", "name", "price", "currency", "category", "stock_quantity", "is_available"]}',
        'Minor update: Added optional "image_urls" array of URIs.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (1, 2, 15, 1,
        '{"type": "object", "properties": {"product_id": {"type": "string", "format": "uuid"}, "name": {"type": "string", "minLength": 3, "maxLength": 200}, "description": {"type": "string", "maxLength": 1000}, "price": {"type": "number", "minimum": 0, "exclusiveMinimum": 0}, "currency": {"type": "string", "pattern": "^[A-Z]{3}$"}, "category": {"type": "string", "enum": ["Electronics", "Books", "Clothing", "Home & Kitchen", "Sports", "Beauty", "Automotive"]}, "stock_quantity": {"type": "integer", "minimum": 0}, "is_available": {"type": "boolean"}, "specifications": {"type": "object", "properties": {"weight_kg": {"type": "number"}, "dimensions_cm": {"type": "string"}, "color": {"type": "string"}}}, "tags": {"type": "array", "items": {"type": "string"}, "uniqueItems": true, "maxItems": 10}, "brand": {"type": "string"}, "created_at": {"type": "string", "format": "date-time"}, "updated_at": {"type": "string", "format": "date-time"}, "avg_rating": {"type": "number", "minimum": 1, "maximum": 5, "default": 0}, "reviews_count": {"type": "integer", "minimum": 0, "default": 0}, "materials": {"type": "array", "items": {"type": "string", "enum": ["Cotton", "Polyester", "Metal", "Plastic", "Wood", "Glass"]}, "uniqueItems": true}, "image_urls": {"type": "array", "items": {"type": "string", "format": "uri"}, "minItems": 1, "maxItems": 5}}, "required": ["product_id", "name", "price", "currency", "category", "stock_quantity", "is_available"]}',
        'Patch: Added default values for avg_rating and reviews_count.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (1, 2, 16, 0,
        '{"type": "object", "properties": {"product_id": {"type": "string", "format": "uuid"}, "name": {"type": "string", "minLength": 3, "maxLength": 200}, "description": {"type": "string", "maxLength": 1000}, "price": {"type": "number", "minimum": 0, "exclusiveMinimum": 0}, "currency": {"type": "string", "pattern": "^[A-Z]{3}$"}, "category": {"type": "string", "enum": ["Electronics", "Books", "Clothing", "Home & Kitchen", "Sports", "Beauty", "Automotive", "Pet Supplies"]}, "stock_quantity": {"type": "integer", "minimum": 0}, "is_available": {"type": "boolean"}, "specifications": {"type": "object", "properties": {"weight_kg": {"type": "number"}, "dimensions_cm": {"type": "string"}, "color": {"type": "string"}}}, "tags": {"type": "array", "items": {"type": "string"}, "uniqueItems": true, "maxItems": 10}, "brand": {"type": "string"}, "created_at": {"type": "string", "format": "date-time"}, "updated_at": {"type": "string", "format": "date-time"}, "avg_rating": {"type": "number", "minimum": 1, "maximum": 5, "default": 0}, "reviews_count": {"type": "integer", "minimum": 0, "default": 0}, "materials": {"type": "array", "items": {"type": "string", "enum": ["Cotton", "Polyester", "Metal", "Plastic", "Wood", "Glass"]}, "uniqueItems": true}, "image_urls": {"type": "array", "items": {"type": "string", "format": "uri"}, "minItems": 1, "maxItems": 5}}, "required": ["product_id", "name", "price", "currency", "category", "stock_quantity", "is_available"]}',
        'Minor update: Added "Pet Supplies" to category enum.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (1, 2, 16, 1,
        '{"type": "object", "properties": {"product_id": {"type": "string", "format": "uuid"}, "name": {"type": "string", "minLength": 3, "maxLength": 200}, "description": {"type": "string", "maxLength": 1000}, "price": {"type": "number", "minimum": 0, "exclusiveMinimum": 0}, "currency": {"type": "string", "pattern": "^[A-Z]{3}$"}, "category": {"type": "string", "enum": ["Electronics", "Books", "Clothing", "Home & Kitchen", "Sports", "Beauty", "Automotive", "Pet Supplies"]}, "stock_quantity": {"type": "integer", "minimum": 0}, "is_available": {"type": "boolean"}, "specifications": {"type": "object", "properties": {"weight_kg": {"type": "number"}, "dimensions_cm": {"type": "string"}, "color": {"type": "string"}}, "required": ["weight_kg", "dimensions_cm"]}, "tags": {"type": "array", "items": {"type": "string"}, "uniqueItems": true, "maxItems": 10}, "brand": {"type": "string"}, "created_at": {"type": "string", "format": "date-time"}, "updated_at": {"type": "string", "format": "date-time"}, "avg_rating": {"type": "number", "minimum": 1, "maximum": 5, "default": 0}, "reviews_count": {"type": "integer", "minimum": 0, "default": 0}, "materials": {"type": "array", "items": {"type": "string", "enum": ["Cotton", "Polyester", "Metal", "Plastic", "Wood", "Glass"]}, "uniqueItems": true}, "image_urls": {"type": "array", "items": {"type": "string", "format": "uri"}, "minItems": 1, "maxItems": 5}}, "required": ["product_id", "name", "price", "currency", "category", "stock_quantity", "is_available"]}',
        'Patch: Made weight_kg and dimensions_cm required within "specifications".');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (1, 2, 17, 0,
        '{"type": "object", "properties": {"product_id": {"type": "string", "format": "uuid"}, "name": {"type": "string", "minLength": 3, "maxLength": 200}, "description": {"type": "string", "maxLength": 1000}, "price": {"type": "number", "minimum": 0, "exclusiveMinimum": 0}, "currency": {"type": "string", "pattern": "^[A-Z]{3}$"}, "category": {"type": "string", "enum": ["Electronics", "Books", "Clothing", "Home & Kitchen", "Sports", "Beauty", "Automotive", "Pet Supplies"]}, "stock_quantity": {"type": "integer", "minimum": 0}, "is_available": {"type": "boolean"}, "specifications": {"type": "object", "properties": {"weight_kg": {"type": "number"}, "dimensions_cm": {"type": "string"}, "color": {"type": "string"}}, "required": ["weight_kg", "dimensions_cm"]}, "tags": {"type": "array", "items": {"type": "string"}, "uniqueItems": true, "maxItems": 10}, "brand": {"type": "string"}, "created_at": {"type": "string", "format": "date-time"}, "updated_at": {"type": "string", "format": "date-time"}, "avg_rating": {"type": "number", "minimum": 1, "maximum": 5, "default": 0}, "reviews_count": {"type": "integer", "minimum": 0, "default": 0}, "materials": {"type": "array", "items": {"type": "string", "enum": ["Cotton", "Polyester", "Metal", "Plastic", "Wood", "Glass"]}, "uniqueItems": true}, "image_urls": {"type": "array", "items": {"type": "string", "format": "uri"}, "minItems": 1, "maxItems": 5}, "ean_code": {"type": "string", "pattern": "^[0-9]{13}$"}}, "required": ["product_id", "name", "price", "currency", "category", "stock_quantity", "is_available"]}',
        'Minor update: Added optional "ean_code" with a pattern constraint.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (1, 2, 17, 1,
        '{"type": "object", "properties": {"product_id": {"type": "string", "format": "uuid"}, "name": {"type": "string", "minLength": 3, "maxLength": 200}, "description": {"type": "string", "maxLength": 1000}, "price": {"type": "number", "minimum": 0, "exclusiveMinimum": 0}, "currency": {"type": "string", "pattern": "^[A-Z]{3}$"}, "category": {"type": "string", "enum": ["Electronics", "Books", "Clothing", "Home & Kitchen", "Sports", "Beauty", "Automotive", "Pet Supplies"]}, "stock_quantity": {"type": "integer", "minimum": 0}, "is_available": {"type": "boolean"}, "specifications": {"type": "object", "properties": {"weight_kg": {"type": "number"}, "dimensions_cm": {"type": "string"}, "color": {"type": "string"}}, "required": ["weight_kg", "dimensions_cm"]}, "tags": {"type": "array", "items": {"type": "string"}, "uniqueItems": true, "maxItems": 10}, "brand": {"type": "string"}, "created_at": {"type": "string", "format": "date-time"}, "updated_at": {"type": "string", "format": "date-time"}, "avg_rating": {"type": "number", "minimum": 1, "maximum": 5, "default": 0}, "reviews_count": {"type": "integer", "minimum": 0, "default": 0}, "materials": {"type": "array", "items": {"type": "string", "enum": ["Cotton", "Polyester", "Metal", "Plastic", "Wood", "Glass"]}, "uniqueItems": true}, "image_urls": {"type": "array", "items": {"type": "string", "format": "uri"}, "minItems": 1, "maxItems": 5}, "ean_code": {"type": "string", "pattern": "^[0-9]{13}$", "description": "European Article Number"}}, "required": ["product_id", "name", "price", "currency", "category", "stock_quantity", "is_available"]}',
        'Patch: Added description to EAN code.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (1, 3, 0, 0,
        '{"type": "object", "properties": {"product_uuid": {"type": "string", "format": "uuid"}, "product_name": {"type": "string", "minLength": 3, "maxLength": 200}, "product_description": {"type": "string", "maxLength": 1000}, "unit_price": {"type": "number", "minimum": 0, "exclusiveMinimum": 0}, "currency_code": {"type": "string", "pattern": "^[A-Z]{3}$"}, "primary_category": {"type": "string", "enum": ["Electronics", "Books", "Clothing", "Home & Kitchen", "Sports", "Beauty", "Automotive", "Pet Supplies"]}, "available_stock": {"type": "integer", "minimum": 0}, "is_active": {"type": "boolean"}, "technical_specs": {"type": "object", "properties": {"weight_kg": {"type": "number"}, "dimensions_cm": {"type": "string"}, "color": {"type": "string"}}, "required": ["weight_kg", "dimensions_cm"]}, "keywords": {"type": "array", "items": {"type": "string"}, "uniqueItems": true, "maxItems": 10}, "manufacturer": {"type": "string"}, "created_timestamp": {"type": "string", "format": "date-time"}, "last_modified_timestamp": {"type": "string", "format": "date-time"}, "average_customer_rating": {"type": "number", "minimum": 1, "maximum": 5, "default": 0}, "customer_review_count": {"type": "integer", "minimum": 0, "default": 0}, "material_composition": {"type": "array", "items": {"type": "string", "enum": ["Cotton", "Polyester", "Metal", "Plastic", "Wood", "Glass"]}, "uniqueItems": true}, "thumbnail_image_urls": {"type": "array", "items": {"type": "string", "format": "uri"}, "minItems": 1, "maxItems": 5}, "ean": {"type": "string", "pattern": "^[0-9]{13}$", "description": "European Article Number"}}, "required": ["product_uuid", "product_name", "unit_price", "currency_code", "primary_category", "available_stock", "is_active"]}',
        'Major update: Renamed several fields for clarity (e.g., product_id to product_uuid, price to unit_price, etc.).');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (1, 3, 0, 1,
        '{"type": "object", "properties": {"product_uuid": {"type": "string", "format": "uuid"}, "product_name": {"type": "string", "minLength": 3, "maxLength": 200}, "product_description": {"type": "string", "maxLength": 1000}, "unit_price": {"type": "number", "minimum": 0, "exclusiveMinimum": 0}, "currency_code": {"type": "string", "pattern": "^[A-Z]{3}$"}, "primary_category": {"type": "string", "enum": ["Electronics", "Books", "Clothing", "Home & Kitchen", "Sports", "Beauty", "Automotive", "Pet Supplies"]}, "available_stock": {"type": "integer", "minimum": 0}, "is_active": {"type": "boolean"}, "technical_specs": {"type": "object", "properties": {"weight_kg": {"type": "number"}, "dimensions_cm": {"type": "string"}, "color": {"type": "string"}}, "required": ["weight_kg", "dimensions_cm"]}, "keywords": {"type": "array", "items": {"type": "string"}, "uniqueItems": true, "maxItems": 10}, "manufacturer": {"type": "string"}, "created_timestamp": {"type": "string", "format": "date-time"}, "last_modified_timestamp": {"type": "string", "format": "date-time"}, "average_customer_rating": {"type": "number", "minimum": 1, "maximum": 5, "default": 0}, "customer_review_count": {"type": "integer", "minimum": 0, "default": 0}, "material_composition": {"type": "array", "items": {"type": "string", "enum": ["Cotton", "Polyester", "Metal", "Plastic", "Wood", "Glass"]}, "uniqueItems": true}, "thumbnail_image_urls": {"type": "array", "items": {"type": "string", "format": "uri"}, "minItems": 1, "maxItems": 5}, "ean": {"type": "string", "pattern": "^[0-9]{13}$", "description": "European Article Number"}, "country_of_origin": {"type": "string", "pattern": "^[A-Z]{2}$"}}, "required": ["product_uuid", "product_name", "unit_price", "currency_code", "primary_category", "available_stock", "is_active"]}',
        'Patch: Added optional "country_of_origin" field with 2-letter ISO code pattern.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (1, 3, 1, 0,
        '{"type": "object", "properties": {"product_uuid": {"type": "string", "format": "uuid"}, "product_name": {"type": "string", "minLength": 3, "maxLength": 200}, "product_description": {"type": "string", "maxLength": 1000}, "unit_price": {"type": "number", "minimum": 0, "exclusiveMinimum": 0}, "currency_code": {"type": "string", "pattern": "^[A-Z]{3}$"}, "primary_category": {"type": "string", "enum": ["Electronics", "Books", "Clothing", "Home & Kitchen", "Sports", "Beauty", "Automotive", "Pet Supplies"]}, "available_stock": {"type": "integer", "minimum": 0}, "is_active": {"type": "boolean"}, "technical_specs": {"type": "object", "properties": {"weight_kg": {"type": "number"}, "dimensions_cm": {"type": "string"}, "color": {"type": "string"}}, "required": ["weight_kg", "dimensions_cm"]}, "keywords": {"type": "array", "items": {"type": "string"}, "uniqueItems": true, "maxItems": 10}, "manufacturer": {"type": "string"}, "created_timestamp": {"type": "string", "format": "date-time"}, "last_modified_timestamp": {"type": "string", "format": "date-time"}, "average_customer_rating": {"type": "number", "minimum": 1, "maximum": 5, "default": 0}, "customer_review_count": {"type": "integer", "minimum": 0, "default": 0}, "material_composition": {"type": "array", "items": {"type": "string", "enum": ["Cotton", "Polyester", "Metal", "Plastic", "Wood", "Glass"]}, "uniqueItems": true}, "thumbnail_image_urls": {"type": "array", "items": {"type": "string", "format": "uri"}, "minItems": 1, "maxItems": 5}, "ean": {"type": "string", "pattern": "^[0-9]{13}$", "description": "European Article Number"}, "country_of_origin": {"type": "string", "pattern": "^[A-Z]{2}$"}, "shipping_info": {"type": "object", "properties": {"delivery_time_days": {"type": "integer", "minimum": 1}, "shipping_cost": {"type": "number", "minimum": 0}}}}, "required": ["product_uuid", "product_name", "unit_price", "currency_code", "primary_category", "available_stock", "is_active"]}',
        'Minor update: Added optional "shipping_info" object with delivery details.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (1, 3, 1, 1,
        '{"type": "object", "properties": {"product_uuid": {"type": "string", "format": "uuid"}, "product_name": {"type": "string", "minLength": 3, "maxLength": 200}, "product_description": {"type": "string", "maxLength": 1000}, "unit_price": {"type": "number", "minimum": 0, "exclusiveMinimum": 0}, "currency_code": {"type": "string", "pattern": "^[A-Z]{3}$"}, "primary_category": {"type": "string", "enum": ["Electronics", "Books", "Clothing", "Home & Kitchen", "Sports", "Beauty", "Automotive", "Pet Supplies"]}, "available_stock": {"type": "integer", "minimum": 0}, "is_active": {"type": "boolean"}, "technical_specs": {"type": "object", "properties": {"weight_kg": {"type": "number"}, "dimensions_cm": {"type": "string"}, "color": {"type": "string"}}, "required": ["weight_kg", "dimensions_cm"]}, "keywords": {"type": "array", "items": {"type": "string"}, "uniqueItems": true, "maxItems": 10}, "manufacturer": {"type": "string"}, "created_timestamp": {"type": "string", "format": "date-time"}, "last_modified_timestamp": {"type": "string", "format": "date-time"}, "average_customer_rating": {"type": "number", "minimum": 1, "maximum": 5, "default": 0}, "customer_review_count": {"type": "integer", "minimum": 0, "default": 0}, "material_composition": {"type": "array", "items": {"type": "string", "enum": ["Cotton", "Polyester", "Metal", "Plastic", "Wood", "Glass"]}, "uniqueItems": true}, "thumbnail_image_urls": {"type": "array", "items": {"type": "string", "format": "uri"}, "minItems": 1, "maxItems": 5}, "ean": {"type": "string", "pattern": "^[0-9]{13}$", "description": "European Article Number"}, "country_of_origin": {"type": "string", "pattern": "^[A-Z]{2}$"}, "shipping_info": {"type": "object", "properties": {"delivery_time_days": {"type": "integer", "minimum": 1}, "shipping_cost": {"type": "number", "minimum": 0}, "ships_from": {"type": "string"}}}, "required": ["product_uuid", "product_name", "unit_price", "currency_code", "primary_category", "available_stock", "is_active"]}',
        'Patch: Added "ships_from" to shipping_info.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (1, 3, 2, 0,
        '{"type": "object", "properties": {"product_uuid": {"type": "string", "format": "uuid"}, "product_name": {"type": "string", "minLength": 3, "maxLength": 200}, "product_description": {"type": "string", "maxLength": 1000}, "unit_price": {"type": "number", "minimum": 0, "exclusiveMinimum": 0}, "currency_code": {"type": "string", "pattern": "^[A-Z]{3}$"}, "primary_category": {"type": "string", "enum": ["Electronics", "Books", "Clothing", "Home & Kitchen", "Sports", "Beauty", "Automotive", "Pet Supplies"]}, "available_stock": {"type": "integer", "minimum": 0}, "is_active": {"type": "boolean"}, "technical_specs": {"type": "object", "properties": {"weight_kg": {"type": "number"}, "dimensions_cm": {"type": "string"}, "color": {"type": "string"}}, "required": ["weight_kg", "dimensions_cm"]}, "keywords": {"type": "array", "items": {"type": "string"}, "uniqueItems": true, "maxItems": 10}, "manufacturer": {"type": "string"}, "created_timestamp": {"type": "string", "format": "date-time"}, "last_modified_timestamp": {"type": "string", "format": "date-time"}, "average_customer_rating": {"type": "number", "minimum": 1, "maximum": 5, "default": 0}, "customer_review_count": {"type": "integer", "minimum": 0, "default": 0}, "material_composition": {"type": "array", "items": {"type": "string", "enum": ["Cotton", "Polyester", "Metal", "Plastic", "Wood", "Glass"]}, "uniqueItems": true}, "thumbnail_image_urls": {"type": "array", "items": {"type": "string", "format": "uri"}, "minItems": 1, "maxItems": 5}, "ean": {"type": "string", "pattern": "^[0-9]{13}$", "description": "European Article Number"}, "country_of_origin": {"type": "string", "pattern": "^[A-Z]{2}$"}, "shipping_info": {"type": "object", "properties": {"delivery_time_days": {"type": "integer", "minimum": 1}, "shipping_cost": {"type": "number", "minimum": 0}, "ships_from": {"type": "string"}}}, "related_product_ids": {"type": "array", "items": {"type": "string", "format": "uuid"}}}, "required": ["product_uuid", "product_name", "unit_price", "currency_code", "primary_category", "available_stock", "is_active"]}',
        'Minor update: Added optional "related_product_ids" array.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (1, 3, 2, 1,
        '{"type": "object", "properties": {"product_uuid": {"type": "string", "format": "uuid"}, "product_name": {"type": "string", "minLength": 3, "maxLength": 200}, "product_description": {"type": "string", "maxLength": 1000}, "unit_price": {"type": "number", "minimum": 0, "exclusiveMinimum": 0}, "currency_code": {"type": "string", "pattern": "^[A-Z]{3}$"}, "primary_category": {"type": "string", "enum": ["Electronics", "Books", "Clothing", "Home & Kitchen", "Sports", "Beauty", "Automotive", "Pet Supplies"]}, "available_stock": {"type": "integer", "minimum": 0}, "is_active": {"type": "boolean"}, "technical_specs": {"type": "object", "properties": {"weight_kg": {"type": "number"}, "dimensions_cm": {"type": "string"}, "color": {"type": "string"}}, "required": ["weight_kg", "dimensions_cm"]}, "keywords": {"type": "array", "items": {"type": "string"}, "uniqueItems": true, "maxItems": 10}, "manufacturer": {"type": "string"}, "created_timestamp": {"type": "string", "format": "date-time"}, "last_modified_timestamp": {"type": "string", "format": "date-time"}, "average_customer_rating": {"type": "number", "minimum": 1, "maximum": 5, "default": 0}, "customer_review_count": {"type": "integer", "minimum": 0, "default": 0}, "material_composition": {"type": "array", "items": {"type": "string", "enum": ["Cotton", "Polyester", "Metal", "Plastic", "Wood", "Glass"]}, "uniqueItems": true}, "thumbnail_image_urls": {"type": "array", "items": {"type": "string", "format": "uri"}, "minItems": 1, "maxItems": 5}, "ean": {"type": "string", "pattern": "^[0-9]{13}$", "description": "European Article Number"}, "country_of_origin": {"type": "string", "pattern": "^[A-Z]{2}$"}, "shipping_info": {"type": "object", "properties": {"delivery_time_days": {"type": "integer", "minimum": 1}, "shipping_cost": {"type": "number", "minimum": 0}, "ships_from": {"type": "string"}}}, "related_product_ids": {"type": "array", "items": {"type": "string", "format": "uuid"}, "maxItems": 5}}, "required": ["product_uuid", "product_name", "unit_price", "currency_code", "primary_category", "available_stock", "is_active"]}',
        'Patch: Added maxItems constraint to related_product_ids.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (2, 3, 2, 0,
        '{"type": "object", "properties": {"user_id": {"type": "string", "format": "uuid"}, "full_name": {"type": "string", "maxLength": 100, "pattern": "^[A-Za-z\\s.''-]+$"}, "email": {"type": "string", "format": "email"}, "phone_number": {"type": "string", "pattern": "^\\+[1-9]\\d{1,14}$"}, "address": {"type": "object", "properties": {"street": {"type": "string", "minLength": 5}, "city": {"type": "string"}, "state": {"type": "string"}, "zip_code": {"type": "string"}, "country": {"type": "string"}}, "required": ["street", "city", "zip_code", "country"]}, "registration_date": {"type": "string", "format": "date"}, "is_active": {"type": "boolean", "default": true}, "preferences": {"type": "object", "properties": {"newsletter": {"type": "boolean"}, "language": {"type": "string", "enum": ["en", "de", "fr"]}}}, "roles": {"type": "array", "items": {"type": "string", "enum": ["admin", "customer", "editor", "guest"]}, "minItems": 1}, "last_login": {"type": "string", "format": "date-time"}, "profile_picture_url": {"type": "string", "format": "uri"}, "marketing_consent": {"type": "boolean", "description": "User consent for marketing communications"}, "consent_timestamp": {"type": "string", "format": "date-time", "description": "Timestamp of marketing consent"}, "social_media_links": {"type": "object", "properties": {"facebook": {"type": "string", "format": "uri"}, "twitter": {"type": "string", "format": "uri"}, "linkedin": {"type": "string", "format": "uri"}, "instagram": {"type": "string", "format": "uri"}}, "minProperties": 1}, "date_of_birth": {"type": "string", "format": "date"}, "last_updated_at": {"type": "string", "format": "date-time"}, "account_status": {"type": "string", "enum": ["active", "suspended", "closed"]}}, "required": ["user_id", "full_name", "email", "registration_date", "is_active", "roles"]}',
        'Minor update: Added "account_status" field with enum values.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (2, 3, 2, 1,
        '{"type": "object", "properties": {"user_id": {"type": "string", "format": "uuid"}, "full_name": {"type": "string", "maxLength": 100, "pattern": "^[A-Za-z\\s.''-]+$"}, "email": {"type": "string", "format": "email"}, "phone_number": {"type": "string", "pattern": "^\\+[1-9]\\d{1,14}$"}, "address": {"type": "object", "properties": {"street": {"type": "string", "minLength": 5}, "city": {"type": "string"}, "state": {"type": "string"}, "zip_code": {"type": "string"}, "country": {"type": "string"}}, "required": ["street", "city", "zip_code", "country"]}, "registration_date": {"type": "string", "format": "date"}, "is_active": {"type": "boolean", "default": true}, "preferences": {"type": "object", "properties": {"newsletter": {"type": "boolean"}, "language": {"type": "string", "enum": ["en", "de", "fr"]}}}, "roles": {"type": "array", "items": {"type": "string", "enum": ["admin", "customer", "editor", "guest"]}, "minItems": 1}, "last_login": {"type": "string", "format": "date-time"}, "profile_picture_url": {"type": "string", "format": "uri"}, "marketing_consent": {"type": "boolean", "description": "User consent for marketing communications"}, "consent_timestamp": {"type": "string", "format": "date-time", "description": "Timestamp of marketing consent"}, "social_media_links": {"type": "object", "properties": {"facebook": {"type": "string", "format": "uri"}, "twitter": {"type": "string", "format": "uri"}, "linkedin": {"type": "string", "format": "uri"}, "instagram": {"type": "string", "format": "uri"}}, "minProperties": 1}, "date_of_birth": {"type": "string", "format": "date"}, "last_updated_at": {"type": "string", "format": "date-time"}, "account_status": {"type": "string", "enum": ["active", "suspended", "closed"]}, "notification_settings": {"type": "object", "properties": {"email_notifications": {"type": "boolean"}, "sms_notifications": {"type": "boolean"}, "push_notifications": {"type": "boolean"}}}}, "required": ["user_id", "full_name", "email", "registration_date", "is_active", "roles"]}',
        'Patch: Added optional "notification_settings" object.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (2, 3, 3, 0,
        '{"type": "object", "properties": {"user_id": {"type": "string", "format": "uuid"}, "full_name": {"type": "string", "maxLength": 100, "pattern": "^[A-Za-z\\s.''-]+$"}, "email": {"type": "string", "format": "email"}, "phone_number": {"type": "string", "pattern": "^\\+[1-9]\\d{1,14}$"}, "address": {"type": "object", "properties": {"street": {"type": "string", "minLength": 5}, "city": {"type": "string"}, "state": {"type": "string"}, "zip_code": {"type": "string"}, "country": {"type": "string"}}, "required": ["street", "city", "zip_code", "country"]}, "registration_date": {"type": "string", "format": "date"}, "is_active": {"type": "boolean", "default": true}, "preferences": {"type": "object", "properties": {"newsletter": {"type": "boolean"}, "language": {"type": "string", "enum": ["en", "de", "fr"]}}}, "roles": {"type": "array", "items": {"type": "string", "enum": ["admin", "customer", "editor", "guest", "moderator"]}, "minItems": 1}, "last_login": {"type": "string", "format": "date-time"}, "profile_picture_url": {"type": "string", "format": "uri"}, "marketing_consent": {"type": "boolean", "description": "User consent for marketing communications"}, "consent_timestamp": {"type": "string", "format": "date-time", "description": "Timestamp of marketing consent"}, "social_media_links": {"type": "object", "properties": {"facebook": {"type": "string", "format": "uri"}, "twitter": {"type": "string", "format": "uri"}, "linkedin": {"type": "string", "format": "uri"}, "instagram": {"type": "string", "format": "uri"}}, "minProperties": 1}, "date_of_birth": {"type": "string", "format": "date"}, "last_updated_at": {"type": "string", "format": "date-time"}, "account_status": {"type": "string", "enum": ["active", "suspended", "closed"]}, "notification_settings": {"type": "object", "properties": {"email_notifications": {"type": "boolean"}, "sms_notifications": {"type": "boolean"}, "push_notifications": {"type": "boolean"}}}}, "required": ["user_id", "full_name", "email", "registration_date", "is_active", "roles"]}',
        'Minor update: Added "moderator" role.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (2, 3, 3, 1,
        '{"type": "object", "properties": {"user_id": {"type": "string", "format": "uuid"}, "full_name": {"type": "string", "maxLength": 100, "pattern": "^[A-Za-z\\s.''-]+$"}, "email": {"type": "string", "format": "email", "uniqueItems": true}, "phone_number": {"type": "string", "pattern": "^\\+[1-9]\\d{1,14}$"}, "address": {"type": "object", "properties": {"street": {"type": "string", "minLength": 5}, "city": {"type": "string"}, "state": {"type": "string"}, "zip_code": {"type": "string"}, "country": {"type": "string"}}, "required": ["street", "city", "zip_code", "country"]}, "registration_date": {"type": "string", "format": "date"}, "is_active": {"type": "boolean", "default": true}, "preferences": {"type": "object", "properties": {"newsletter": {"type": "boolean"}, "language": {"type": "string", "enum": ["en", "de", "fr"]}}}, "roles": {"type": "array", "items": {"type": "string", "enum": ["admin", "customer", "editor", "guest", "moderator"]}, "minItems": 1}, "last_login": {"type": "string", "format": "date-time"}, "profile_picture_url": {"type": "string", "format": "uri"}, "marketing_consent": {"type": "boolean", "description": "User consent for marketing communications"}, "consent_timestamp": {"type": "string", "format": "date-time", "description": "Timestamp of marketing consent"}, "social_media_links": {"type": "object", "properties": {"facebook": {"type": "string", "format": "uri"}, "twitter": {"type": "string", "format": "uri"}, "linkedin": {"type": "string", "format": "uri"}, "instagram": {"type": "string", "format": "uri"}}, "minProperties": 1}, "date_of_birth": {"type": "string", "format": "date"}, "last_updated_at": {"type": "string", "format": "date-time"}, "account_status": {"type": "string", "enum": ["active", "suspended", "closed"]}, "notification_settings": {"type": "object", "properties": {"email_notifications": {"type": "boolean"}, "sms_notifications": {"type": "boolean"}, "push_notifications": {"type": "boolean"}}}}, "required": ["user_id", "full_name", "email", "registration_date", "is_active", "roles"]}',
        'Patch: Added uniqueItems constraint to email field.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (2, 3, 4, 0,
        '{"type": "object", "properties": {"user_id": {"type": "string", "format": "uuid"}, "full_name": {"type": "string", "maxLength": 100, "pattern": "^[A-Za-z\\s.''-]+$"}, "email": {"type": "string", "format": "email", "uniqueItems": true}, "phone_number": {"type": "string", "pattern": "^\\+[1-9]\\d{1,14}$"}, "address": {"type": "object", "properties": {"street": {"type": "string", "minLength": 5}, "city": {"type": "string"}, "state": {"type": "string"}, "zip_code": {"type": "string"}, "country": {"type": "string"}, "address_type": {"type": "string", "enum": ["billing", "shipping", "primary"]}}, "required": ["street", "city", "zip_code", "country"]}, "registration_date": {"type": "string", "format": "date"}, "is_active": {"type": "boolean", "default": true}, "preferences": {"type": "object", "properties": {"newsletter": {"type": "boolean"}, "language": {"type": "string", "enum": ["en", "de", "fr"]}}}, "roles": {"type": "array", "items": {"type": "string", "enum": ["admin", "customer", "editor", "guest", "moderator"]}, "minItems": 1}, "last_login": {"type": "string", "format": "date-time"}, "profile_picture_url": {"type": "string", "format": "uri"}, "marketing_consent": {"type": "boolean", "description": "User consent for marketing communications"}, "consent_timestamp": {"type": "string", "format": "date-time", "description": "Timestamp of marketing consent"}, "social_media_links": {"type": "object", "properties": {"facebook": {"type": "string", "format": "uri"}, "twitter": {"type": "string", "format": "uri"}, "linkedin": {"type": "string", "format": "uri"}, "instagram": {"type": "string", "format": "uri"}}, "minProperties": 1}, "date_of_birth": {"type": "string", "format": "date"}, "last_updated_at": {"type": "string", "format": "date-time"}, "account_status": {"type": "string", "enum": ["active", "suspended", "closed"]}, "notification_settings": {"type": "object", "properties": {"email_notifications": {"type": "boolean"}, "sms_notifications": {"type": "boolean"}, "push_notifications": {"type": "boolean"}}}}, "required": ["user_id", "full_name", "email", "registration_date", "is_active", "roles"]}',
        'Minor update: Added "address_type" to address object.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (2, 3, 4, 1,
        '{"type": "object", "properties": {"user_id": {"type": "string", "format": "uuid"}, "full_name": {"type": "string", "maxLength": 100, "pattern": "^[A-Za-z\\s.''-]+$"}, "email": {"type": "string", "format": "email", "uniqueItems": true}, "phone_number": {"type": "string", "pattern": "^\\+[1-9]\\d{1,14}$"}, "address": {"type": "object", "properties": {"street": {"type": "string", "minLength": 5}, "city": {"type": "string"}, "state": {"type": "string"}, "zip_code": {"type": "string", "pattern": "^[0-9]{5}(?:-[0-9]{4})?$"}, "country": {"type": "string"}, "address_type": {"type": "string", "enum": ["billing", "shipping", "primary"]}}, "required": ["street", "city", "zip_code", "country"]}, "registration_date": {"type": "string", "format": "date"}, "is_active": {"type": "boolean", "default": true}, "preferences": {"type": "object", "properties": {"newsletter": {"type": "boolean"}, "language": {"type": "string", "enum": ["en", "de", "fr"]}}}, "roles": {"type": "array", "items": {"type": "string", "enum": ["admin", "customer", "editor", "guest", "moderator"]}, "minItems": 1}, "last_login": {"type": "string", "format": "date-time"}, "profile_picture_url": {"type": "string", "format": "uri"}, "marketing_consent": {"type": "boolean", "description": "User consent for marketing communications"}, "consent_timestamp": {"type": "string", "format": "date-time", "description": "Timestamp of marketing consent"}, "social_media_links": {"type": "object", "properties": {"facebook": {"type": "string", "format": "uri"}, "twitter": {"type": "string", "format": "uri"}, "linkedin": {"type": "string", "format": "uri"}, "instagram": {"type": "string", "format": "uri"}}, "minProperties": 1}, "date_of_birth": {"type": "string", "format": "date"}, "last_updated_at": {"type": "string", "format": "date-time"}, "account_status": {"type": "string", "enum": ["active", "suspended", "closed"]}, "notification_settings": {"type": "object", "properties": {"email_notifications": {"type": "boolean"}, "sms_notifications": {"type": "boolean"}, "push_notifications": {"type": "boolean"}}}}, "required": ["user_id", "full_name", "email", "registration_date", "is_active", "roles"]}',
        'Patch: Added zip code pattern validation.');

-- Versions for 'order_event_schema' (id = 3) - Continuing and adding more variations (aiming for 20+ total versions)
-- Previous highest version was 3.2.4.0 (incomplete from last prompt) or 3.2.3.1 (from my last full generation). Let's start from 3.2.4.0 complete.
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (3, 2, 4, 0,
        '{"type": "object", "properties": {"event_id": {"type": "string", "format": "uuid"}, "order_id": {"type": "string", "format": "uuid"}, "customer_id": {"type": "string", "format": "uuid", "description": "Refers to user_id in user_profile_schema"}, "event_type": {"type": "string", "enum": ["ORDER_CREATED", "ORDER_UPDATED", "ORDER_CANCELLED", "ORDER_SHIPPED", "ORDER_DELIVERED", "PAYMENT_RECEIVED", "REFUND_ISSUED", "ORDER_ARCHIVED"]}, "event_timestamp": {"type": "string", "format": "date-time"}, "actor_id": {"type": "string", "format": "uuid", "description": "ID of the user or system performing the action"}, "comment": {"type": "string", "maxLength": 500}, "source_system": {"type": "string", "enum": ["web", "mobile", "api", "admin_panel"]}, "transaction_context": {"type": "object", "properties": {"ip_address": {"type": "string", "format": "ipv4"}, "user_agent": {"type": "string"}}}, "payload": {"type": "object", "properties": {"status": {"type": "string", "enum": ["pending", "processing", "shipped", "delivered", "cancelled", "paid", "refunded", "archived"]}, "total_amount": {"type": "number", "minimum": 0}, "currency": {"type": "string", "pattern": "^[A-Z]{3}$"}, "items": {"type": "array", "items": {"type": "object", "properties": {"product_id": {"type": "string"}, "product_name": {"type": "string"}, "quantity": {"type": "integer", "minimum": 1}, "price_per_unit": {"type": "number", "minimum": 0}}, "required": ["product_id", "product_name", "quantity", "price_per_unit"]}, "minItems": 1}, "shipping_address": {"type": "object", "properties": {"street": {"type": "string", "minLength": 5}, "city": {"type": "string"}, "state": {"type": "string"}, "zip_code": {"type": "string"}, "country": {"type": "string"}}, "required": ["street", "city", "zip_code", "country"]}, "payment_info": {"type": "object", "properties": {"method": {"type": "string", "enum": ["credit_card", "paypal", "bank_transfer"]}, "transaction_id": {"type": "string"}}, "required": ["method", "transaction_id"]}}, "required": ["status", "total_amount", "currency", "items"]}}, "required": ["event_id", "order_id", "customer_id", "event_type", "event_timestamp", "actor_id", "payload"]}',
        'Minor update: Added optional "transaction_context" object with ip and user agent.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (3, 2, 4, 1,
        '{"type": "object", "properties": {"event_id": {"type": "string", "format": "uuid"}, "order_id": {"type": "string", "format": "uuid"}, "customer_id": {"type": "string", "format": "uuid", "description": "Refers to user_id in user_profile_schema"}, "event_type": {"type": "string", "enum": ["ORDER_CREATED", "ORDER_UPDATED", "ORDER_CANCELLED", "ORDER_SHIPPED", "ORDER_DELIVERED", "PAYMENT_RECEIVED", "REFUND_ISSUED", "ORDER_ARCHIVED"]}, "event_timestamp": {"type": "string", "format": "date-time"}, "actor_id": {"type": "string", "format": "uuid", "description": "ID of the user or system performing the action"}, "comment": {"type": "string", "maxLength": 500}, "source_system": {"type": "string", "enum": ["web", "mobile", "api", "admin_panel"]}, "transaction_context": {"type": "object", "properties": {"ip_address": {"type": "string", "format": "ipv4"}, "user_agent": {"type": "string"}}}, "payload": {"type": "object", "properties": {"status": {"type": "string", "enum": ["pending", "processing", "shipped", "delivered", "cancelled", "paid", "refunded", "archived"]}, "total_amount": {"type": "number", "minimum": 0}, "currency": {"type": "string", "pattern": "^[A-Z]{3}$"}, "items": {"type": "array", "items": {"type": "object", "properties": {"product_id": {"type": "string"}, "product_name": {"type": "string"}, "quantity": {"type": "integer", "minimum": 1}, "price_per_unit": {"type": "number", "minimum": 0}, "sku": {"type": "string"}}, "required": ["product_id", "product_name", "quantity", "price_per_unit"]}, "minItems": 1}, "shipping_address": {"type": "object", "properties": {"street": {"type": "string", "minLength": 5}, "city": {"type": "string"}, "state": {"type": "string"}, "zip_code": {"type": "string"}, "country": {"type": "string"}}, "required": ["street", "city", "zip_code", "country"]}, "payment_info": {"type": "object", "properties": {"method": {"type": "string", "enum": ["credit_card", "paypal", "bank_transfer"]}, "transaction_id": {"type": "string"}}, "required": ["method", "transaction_id"]}}, "required": ["status", "total_amount", "currency", "items"]}}, "required": ["event_id", "order_id", "customer_id", "event_type", "event_timestamp", "actor_id", "payload"]}',
        'Patch: Added "sku" to items object within payload.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (3, 2, 5, 0,
        '{"type": "object", "properties": {"event_id": {"type": "string", "format": "uuid"}, "order_id": {"type": "string", "format": "uuid"}, "customer_id": {"type": "string", "format": "uuid", "description": "Refers to user_id in user_profile_schema"}, "event_type": {"type": "string", "enum": ["ORDER_CREATED", "ORDER_UPDATED", "ORDER_CANCELLED", "ORDER_SHIPPED", "ORDER_DELIVERED", "PAYMENT_RECEIVED", "REFUND_ISSUED", "ORDER_ARCHIVED"]}, "event_timestamp": {"type": "string", "format": "date-time"}, "actor_id": {"type": "string", "format": "uuid", "description": "ID of the user or system performing the action"}, "comment": {"type": "string", "maxLength": 500}, "source_system": {"type": "string", "enum": ["web", "mobile", "api", "admin_panel"]}, "transaction_context": {"type": "object", "properties": {"ip_address": {"type": "string", "format": "ipv4"}, "user_agent": {"type": "string"}, "device_type": {"type": "string", "enum": ["desktop", "mobile", "tablet"]}}}, "payload": {"type": "object", "properties": {"status": {"type": "string", "enum": ["pending", "processing", "shipped", "delivered", "cancelled", "paid", "refunded", "archived"]}, "total_amount": {"type": "number", "minimum": 0}, "currency": {"type": "string", "pattern": "^[A-Z]{3}$"}, "items": {"type": "array", "items": {"type": "object", "properties": {"product_id": {"type": "string"}, "product_name": {"type": "string"}, "quantity": {"type": "integer", "minimum": 1}, "price_per_unit": {"type": "number", "minimum": 0}, "sku": {"type": "string"}}, "required": ["product_id", "product_name", "quantity", "price_per_unit"]}, "minItems": 1}, "shipping_address": {"type": "object", "properties": {"street": {"type": "string", "minLength": 5}, "city": {"type": "string"}, "state": {"type": "string"}, "zip_code": {"type": "string"}, "country": {"type": "string"}}, "required": ["street", "city", "zip_code", "country"]}, "payment_info": {"type": "object", "properties": {"method": {"type": "string", "enum": ["credit_card", "paypal", "bank_transfer"]}, "transaction_id": {"type": "string"}}, "required": ["method", "transaction_id"]}}, "required": ["status", "total_amount", "currency", "items"]}}, "required": ["event_id", "order_id", "customer_id", "event_type", "event_timestamp", "actor_id", "payload"]}',
        'Minor update: Added "device_type" to transaction_context.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (3, 2, 5, 1,
        '{"type": "object", "properties": {"event_id": {"type": "string", "format": "uuid"}, "order_id": {"type": "string", "format": "uuid"}, "customer_id": {"type": "string", "format": "uuid", "description": "Refers to user_id in user_profile_schema"}, "event_type": {"type": "string", "enum": ["ORDER_CREATED", "ORDER_UPDATED", "ORDER_CANCELLED", "ORDER_SHIPPED", "ORDER_DELIVERED", "PAYMENT_RECEIVED", "REFUND_ISSUED", "ORDER_ARCHIVED"]}, "event_timestamp": {"type": "string", "format": "date-time"}, "actor_id": {"type": "string", "format": "uuid", "description": "ID of the user or system performing the action"}, "comment": {"type": "string", "maxLength": 500}, "source_system": {"type": "string", "enum": ["web", "mobile", "api", "admin_panel"]}, "transaction_context": {"type": "object", "properties": {"ip_address": {"type": "string", "format": "ipv4"}, "user_agent": {"type": "string"}, "device_type": {"type": "string", "enum": ["desktop", "mobile", "tablet"]}}}, "payload": {"type": "object", "properties": {"status": {"type": "string", "enum": ["pending", "processing", "shipped", "delivered", "cancelled", "paid", "refunded", "archived"]}, "total_amount": {"type": "number", "minimum": 0}, "currency": {"type": "string", "pattern": "^[A-Z]{3}$"}, "items": {"type": "array", "items": {"type": "object", "properties": {"product_id": {"type": "string"}, "product_name": {"type": "string"}, "quantity": {"type": "integer", "minimum": 1}, "price_per_unit": {"type": "number", "minimum": 0}, "sku": {"type": "string"}}, "required": ["product_id", "product_name", "quantity", "price_per_unit"]}, "minItems": 1}, "shipping_address": {"type": "object", "properties": {"street": {"type": "string", "minLength": 5}, "city": {"type": "string"}, "state": {"type": "string"}, "zip_code": {"type": "string"}, "country": {"type": "string"}}, "required": ["street", "city", "zip_code", "country"]}, "payment_info": {"type": "object", "properties": {"method": {"type": "string", "enum": ["credit_card", "paypal", "bank_transfer"]}, "transaction_id": {"type": "string"}}, "required": ["method", "transaction_id"]}, "tracking_number": {"type": "string"}}, "required": ["status", "total_amount", "currency", "items"]}}, "required": ["event_id", "order_id", "customer_id", "event_type", "event_timestamp", "actor_id", "payload"]}',
        'Patch: Added optional "tracking_number" to payload.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (3, 2, 6, 0,
        '{"type": "object", "properties": {"event_id": {"type": "string", "format": "uuid"}, "order_id": {"type": "string", "format": "uuid"}, "customer_id": {"type": "string", "format": "uuid", "description": "Refers to user_id in user_profile_schema"}, "event_type": {"type": "string", "enum": ["ORDER_CREATED", "ORDER_UPDATED", "ORDER_CANCELLED", "ORDER_SHIPPED", "ORDER_DELIVERED", "PAYMENT_RECEIVED", "REFUND_ISSUED", "ORDER_ARCHIVED", "ORDER_RETURNED"]}, "event_timestamp": {"type": "string", "format": "date-time"}, "actor_id": {"type": "string", "format": "uuid", "description": "ID of the user or system performing the action"}, "comment": {"type": "string", "maxLength": 500}, "source_system": {"type": "string", "enum": ["web", "mobile", "api", "admin_panel"]}, "transaction_context": {"type": "object", "properties": {"ip_address": {"type": "string", "format": "ipv4"}, "user_agent": {"type": "string"}, "device_type": {"type": "string", "enum": ["desktop", "mobile", "tablet"]}}}, "payload": {"type": "object", "properties": {"status": {"type": "string", "enum": ["pending", "processing", "shipped", "delivered", "cancelled", "paid", "refunded", "archived", "returned"]}, "total_amount": {"type": "number", "minimum": 0}, "currency": {"type": "string", "pattern": "^[A-Z]{3}$"}, "items": {"type": "array", "items": {"type": "object", "properties": {"product_id": {"type": "string"}, "product_name": {"type": "string"}, "quantity": {"type": "integer", "minimum": 1}, "price_per_unit": {"type": "number", "minimum": 0}, "sku": {"type": "string"}}, "required": ["product_id", "product_name", "quantity", "price_per_unit"]}, "minItems": 1}, "shipping_address": {"type": "object", "properties": {"street": {"type": "string", "minLength": 5}, "city": {"type": "string"}, "state": {"type": "string"}, "zip_code": {"type": "string"}, "country": {"type": "string"}}, "required": ["street", "city", "zip_code", "country"]}, "payment_info": {"type": "object", "properties": {"method": {"type": "string", "enum": ["credit_card", "paypal", "bank_transfer"]}, "transaction_id": {"type": "string"}}, "required": ["method", "transaction_id"]}, "tracking_number": {"type": "string"}}, "required": ["status", "total_amount", "currency", "items"]}}, "required": ["event_id", "order_id", "customer_id", "event_type", "event_timestamp", "actor_id", "payload"]}',
        'Minor update: Added "ORDER_RETURNED" event type and status.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (3, 2, 6, 1,
        '{"type": "object", "properties": {"event_id": {"type": "string", "format": "uuid"}, "order_id": {"type": "string", "format": "uuid"}, "customer_id": {"type": "string", "format": "uuid", "description": "Refers to user_id in user_profile_schema"}, "event_type": {"type": "string", "enum": ["ORDER_CREATED", "ORDER_UPDATED", "ORDER_CANCELLED", "ORDER_SHIPPED", "ORDER_DELIVERED", "PAYMENT_RECEIVED", "REFUND_ISSUED", "ORDER_ARCHIVED", "ORDER_RETURNED"]}, "event_timestamp": {"type": "string", "format": "date-time"}, "actor_id": {"type": "string", "format": "uuid", "description": "ID of the user or system performing the action"}, "comment": {"type": "string", "maxLength": 500}, "source_system": {"type": "string", "enum": ["web", "mobile", "api", "admin_panel"]}, "transaction_context": {"type": "object", "properties": {"ip_address": {"type": "string", "format": "ipv4"}, "user_agent": {"type": "string"}, "device_type": {"type": "string", "enum": ["desktop", "mobile", "tablet"]}}}, "payload": {"type": "object", "properties": {"status": {"type": "string", "enum": ["pending", "processing", "shipped", "delivered", "cancelled", "paid", "refunded", "archived", "returned"]}, "total_amount": {"type": "number", "minimum": 0}, "currency": {"type": "string", "pattern": "^[A-Z]{3}$"}, "items": {"type": "array", "items": {"type": "object", "properties": {"product_id": {"type": "string"}, "product_name": {"type": "string"}, "quantity": {"type": "integer", "minimum": 1}, "price_per_unit": {"type": "number", "minimum": 0}, "sku": {"type": "string"}, "reason_for_return": {"type": "string"}}, "required": ["product_id", "product_name", "quantity", "price_per_unit"]}, "minItems": 1}, "shipping_address": {"type": "object", "properties": {"street": {"type": "string", "minLength": 5}, "city": {"type": "string"}, "state": {"type": "string"}, "zip_code": {"type": "string"}, "country": {"type": "string"}}, "required": ["street", "city", "zip_code", "country"]}, "payment_info": {"type": "object", "properties": {"method": {"type": "string", "enum": ["credit_card", "paypal", "bank_transfer"]}, "transaction_id": {"type": "string"}}, "required": ["method", "transaction_id"]}, "tracking_number": {"type": "string"}}, "required": ["status", "total_amount", "currency", "items"]}}, "required": ["event_id", "order_id", "customer_id", "event_type", "event_timestamp", "actor_id", "payload"]}',
        'Patch: Added optional "reason_for_return" to items for ORDER_RETURNED events.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (3, 2, 7, 0,
        '{"type": "object", "properties": {"event_id": {"type": "string", "format": "uuid"}, "order_id": {"type": "string", "format": "uuid"}, "customer_id": {"type": "string", "format": "uuid", "description": "Refers to user_id in user_profile_schema"}, "event_type": {"type": "string", "enum": ["ORDER_CREATED", "ORDER_UPDATED", "ORDER_CANCELLED", "ORDER_SHIPPED", "ORDER_DELIVERED", "PAYMENT_RECEIVED", "REFUND_ISSUED", "ORDER_ARCHIVED", "ORDER_RETURNED"]}, "event_timestamp": {"type": "string", "format": "date-time"}, "actor_id": {"type": "string", "format": "uuid", "description": "ID of the user or system performing the action"}, "comment": {"type": "string", "maxLength": 500}, "source_system": {"type": "string", "enum": ["web", "mobile", "api", "admin_panel"]}, "transaction_context": {"type": "object", "properties": {"ip_address": {"type": "string", "format": "ipv4"}, "user_agent": {"type": "string"}, "device_type": {"type": "string", "enum": ["desktop", "mobile", "tablet"]}}}, "payload": {"type": "object", "properties": {"status": {"type": "string", "enum": ["pending", "processing", "shipped", "delivered", "cancelled", "paid", "refunded", "archived", "returned"]}, "total_amount": {"type": "number", "minimum": 0}, "currency": {"type": "string", "pattern": "^[A-Z]{3}$"}, "items": {"type": "array", "items": {"type": "object", "properties": {"product_id": {"type": "string"}, "product_name": {"type": "string"}, "quantity": {"type": "integer", "minimum": 1}, "price_per_unit": {"type": "number", "minimum": 0}, "sku": {"type": "string"}, "reason_for_return": {"type": "string"}}, "required": ["product_id", "product_name", "quantity", "price_per_unit"]}, "minItems": 1}, "shipping_address": {"type": "object", "properties": {"street": {"type": "string", "minLength": 5}, "city": {"type": "string"}, "state": {"type": "string"}, "zip_code": {"type": "string"}, "country": {"type": "string"}}, "required": ["street", "city", "zip_code", "country"]}, "payment_info": {"type": "object", "properties": {"method": {"type": "string", "enum": ["credit_card", "paypal", "bank_transfer"]}, "transaction_id": {"type": "string"}}, "required": ["method", "transaction_id"]}, "tracking_number": {"type": "string"}, "estimated_delivery_date": {"type": "string", "format": "date"}}, "required": ["status", "total_amount", "currency", "items"]}}, "required": ["event_id", "order_id", "customer_id", "event_type", "event_timestamp", "actor_id", "payload"]}',
        'Minor update: Added optional "estimated_delivery_date" to payload.');

-- Versions for 'payment_transaction_schema' (id = 4) - New Schema
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (4, 1, 0, 0,
        '{"type": "object", "properties": {"transaction_id": {"type": "string", "format": "uuid"}, "order_id": {"type": "string", "format": "uuid"}, "user_id": {"type": "string", "format": "uuid"}, "amount": {"type": "number", "minimum": 0, "exclusiveMinimum": 0}, "currency": {"type": "string", "pattern": "^[A-Z]{3}$"}, "status": {"type": "string", "enum": ["pending", "completed", "failed", "refunded"]}, "payment_method": {"type": "string", "enum": ["credit_card", "paypal", "bank_transfer", "crypto"]}, "timestamp": {"type": "string", "format": "date-time"}}, "required": ["transaction_id", "order_id", "user_id", "amount", "currency", "status", "payment_method", "timestamp"]}',
        'Initial version of payment transaction schema.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (4, 1, 1, 0,
        '{"type": "object", "properties": {"transaction_id": {"type": "string", "format": "uuid"}, "order_id": {"type": "string", "format": "uuid"}, "user_id": {"type": "string", "format": "uuid"}, "amount": {"type": "number", "minimum": 0, "exclusiveMinimum": 0}, "currency": {"type": "string", "pattern": "^[A-Z]{3}$"}, "status": {"type": "string", "enum": ["pending", "completed", "failed", "refunded", "disputed"]}, "payment_method": {"type": "string", "enum": ["credit_card", "paypal", "bank_transfer", "crypto"]}, "timestamp": {"type": "string", "format": "date-time"}, "processor_response_code": {"type": "string"}}, "required": ["transaction_id", "order_id", "user_id", "amount", "currency", "status", "payment_method", "timestamp"]}',
        'Minor update: Added "disputed" status and optional "processor_response_code".');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (4, 1, 1, 1,
        '{"type": "object", "properties": {"transaction_id": {"type": "string", "format": "uuid"}, "order_id": {"type": "string", "format": "uuid"}, "user_id": {"type": "string", "format": "uuid"}, "amount": {"type": "number", "minimum": 0, "exclusiveMinimum": 0}, "currency": {"type": "string", "pattern": "^[A-Z]{3}$"}, "status": {"type": "string", "enum": ["pending", "completed", "failed", "refunded", "disputed"]}, "payment_method": {"type": "string", "enum": ["credit_card", "paypal", "bank_transfer", "crypto"]}, "timestamp": {"type": "string", "format": "date-time"}, "processor_response_code": {"type": "string"}, "error_message": {"type": "string", "maxLength": 500}}, "required": ["transaction_id", "order_id", "user_id", "amount", "currency", "status", "payment_method", "timestamp"]}',
        'Patch: Added optional "error_message" for failed transactions.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (4, 1, 2, 0,
        '{"type": "object", "properties": {"transaction_id": {"type": "string", "format": "uuid"}, "order_id": {"type": "string", "format": "uuid"}, "user_id": {"type": "string", "format": "uuid"}, "amount": {"type": "number", "minimum": 0, "exclusiveMinimum": 0}, "currency": {"type": "string", "pattern": "^[A-Z]{3}$"}, "status": {"type": "string", "enum": ["pending", "completed", "failed", "refunded", "disputed"]}, "payment_method": {"type": "string", "enum": ["credit_card", "paypal", "bank_transfer", "crypto"]}, "timestamp": {"type": "string", "format": "date-time"}, "processor_response_code": {"type": "string"}, "error_message": {"type": "string", "maxLength": 500}, "billing_address_snapshot": {"type": "object", "properties": {"street": {"type": "string"}, "city": {"type": "string"}, "zip_code": {"type": "string"}, "country": {"type": "string"}}}}, "required": ["transaction_id", "order_id", "user_id", "amount", "currency", "status", "payment_method", "timestamp"]}',
        'Minor update: Added optional "billing_address_snapshot" object.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (4, 1, 2, 1,
        '{"type": "object", "properties": {"transaction_id": {"type": "string", "format": "uuid"}, "order_id": {"type": "string", "format": "uuid"}, "user_id": {"type": "string", "format": "uuid"}, "amount": {"type": "number", "minimum": 0, "exclusiveMinimum": 0}, "currency": {"type": "string", "pattern": "^[A-Z]{3}$"}, "status": {"type": "string", "enum": ["pending", "completed", "failed", "refunded", "disputed"]}, "payment_method": {"type": "string", "enum": ["credit_card", "paypal", "bank_transfer", "crypto"]}, "timestamp": {"type": "string", "format": "date-time"}, "processor_response_code": {"type": "string"}, "error_message": {"type": "string", "maxLength": 500}, "billing_address_snapshot": {"type": "object", "properties": {"street": {"type": "string"}, "city": {"type": "string"}, "state": {"type": "string"}, "zip_code": {"type": "string"}, "country": {"type": "string"}}}, "transaction_fee": {"type": "number", "minimum": 0}}, "required": ["transaction_id", "order_id", "user_id", "amount", "currency", "status", "payment_method", "timestamp"]}',
        'Patch: Added "state" to billing address snapshot and optional "transaction_fee".');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (4, 1, 3, 0,
        '{"type": "object", "properties": {"transaction_id": {"type": "string", "format": "uuid"}, "order_id": {"type": "string", "format": "uuid"}, "user_id": {"type": "string", "format": "uuid"}, "amount": {"type": "number", "minimum": 0, "exclusiveMinimum": 0}, "currency": {"type": "string", "pattern": "^[A-Z]{3}$"}, "status": {"type": "string", "enum": ["pending", "completed", "failed", "refunded", "disputed", "voided"]}, "payment_method": {"type": "string", "enum": ["credit_card", "paypal", "bank_transfer", "crypto"]}, "timestamp": {"type": "string", "format": "date-time"}, "processor_response_code": {"type": "string"}, "error_message": {"type": "string", "maxLength": 500}, "billing_address_snapshot": {"type": "object", "properties": {"street": {"type": "string"}, "city": {"type": "string"}, "state": {"type": "string"}, "zip_code": {"type": "string"}, "country": {"type": "string"}}}, "transaction_fee": {"type": "number", "minimum": 0}, "external_transaction_ref": {"type": "string"}}, "required": ["transaction_id", "order_id", "user_id", "amount", "currency", "status", "payment_method", "timestamp"]}',
        'Minor update: Added "voided" status and optional "external_transaction_ref".');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (4, 1, 3, 1,
        '{"type": "object", "properties": {"transaction_id": {"type": "string", "format": "uuid"}, "order_id": {"type": "string", "format": "uuid"}, "user_id": {"type": "string", "format": "uuid"}, "amount": {"type": "number", "minimum": 0, "exclusiveMinimum": 0}, "currency": {"type": "string", "pattern": "^[A-Z]{3}$"}, "status": {"type": "string", "enum": ["pending", "completed", "failed", "refunded", "disputed", "voided"]}, "payment_method": {"type": "string", "enum": ["credit_card", "paypal", "bank_transfer", "crypto"]}, "timestamp": {"type": "string", "format": "date-time"}, "processor_response_code": {"type": "string"}, "error_message": {"type": "string", "maxLength": 500}, "billing_address_snapshot": {"type": "object", "properties": {"street": {"type": "string"}, "city": {"type": "string"}, "state": {"type": "string"}, "zip_code": {"type": "string"}, "country": {"type": "string"}}, "required": ["street", "city", "country"]}, "transaction_fee": {"type": "number", "minimum": 0}, "external_transaction_ref": {"type": "string"}}, "required": ["transaction_id", "order_id", "user_id", "amount", "currency", "status", "payment_method", "timestamp"]}',
        'Patch: Made billing_address_snapshot fields street, city, country required.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (4, 1, 4, 0,
        '{"type": "object", "properties": {"transaction_id": {"type": "string", "format": "uuid"}, "order_id": {"type": "string", "format": "uuid"}, "user_id": {"type": "string", "format": "uuid"}, "amount": {"type": "number", "minimum": 0, "exclusiveMinimum": 0}, "currency": {"type": "string", "pattern": "^[A-Z]{3}$"}, "status": {"type": "string", "enum": ["pending", "completed", "failed", "refunded", "disputed", "voided"]}, "payment_method": {"type": "string", "enum": ["credit_card", "paypal", "bank_transfer", "crypto"]}, "timestamp": {"type": "string", "format": "date-time"}, "processor_response_code": {"type": "string"}, "error_message": {"type": "string", "maxLength": 500}, "billing_address_snapshot": {"type": "object", "properties": {"street": {"type": "string"}, "city": {"type": "string"}, "state": {"type": "string"}, "zip_code": {"type": "string"}, "country": {"type": "string"}}, "required": ["street", "city", "country"]}, "transaction_fee": {"type": "number", "minimum": 0}, "external_transaction_ref": {"type": "string"}, "ip_address": {"type": "string", "format": "ipv4"}}, "required": ["transaction_id", "order_id", "user_id", "amount", "currency", "status", "payment_method", "timestamp"]}',
        'Minor update: Added optional "ip_address" for transaction origin.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (4, 1, 4, 1,
        '{"type": "object", "properties": {"transaction_id": {"type": "string", "format": "uuid"}, "order_id": {"type": "string", "format": "uuid"}, "user_id": {"type": "string", "format": "uuid"}, "amount": {"type": "number", "minimum": 0, "exclusiveMinimum": 0}, "currency": {"type": "string", "pattern": "^[A-Z]{3}$"}, "status": {"type": "string", "enum": ["pending", "completed", "failed", "refunded", "disputed", "voided"]}, "payment_method": {"type": "string", "enum": ["credit_card", "paypal", "bank_transfer", "crypto"]}, "timestamp": {"type": "string", "format": "date-time"}, "processor_response_code": {"type": "string"}, "error_message": {"type": "string", "maxLength": 500}, "billing_address_snapshot": {"type": "object", "properties": {"street": {"type": "string"}, "city": {"type": "string"}, "state": {"type": "string"}, "zip_code": {"type": "string"}, "country": {"type": "string"}}, "required": ["street", "city", "country"]}, "transaction_fee": {"type": "number", "minimum": 0}, "external_transaction_ref": {"type": "string"}, "ip_address": {"type": "string", "format": "ipv4"}, "user_agent": {"type": "string"}}, "required": ["transaction_id", "order_id", "user_id", "amount", "currency", "status", "payment_method", "timestamp"]}',
        'Patch: Added optional "user_agent".');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (4, 1, 5, 0,
        '{"type": "object", "properties": {"transaction_id": {"type": "string", "format": "uuid"}, "order_id": {"type": "string", "format": "uuid"}, "user_id": {"type": "string", "format": "uuid"}, "amount": {"type": "number", "minimum": 0, "exclusiveMinimum": 0}, "currency": {"type": "string", "pattern": "^[A-Z]{3}$"}, "status": {"type": "string", "enum": ["pending", "completed", "failed", "refunded", "disputed", "voided"]}, "payment_method": {"type": "string", "enum": ["credit_card", "paypal", "bank_transfer", "crypto"]}, "timestamp": {"type": "string", "format": "date-time"}, "processor_response_code": {"type": "string"}, "error_message": {"type": "string", "maxLength": 500}, "billing_address_snapshot": {"type": "object", "properties": {"street": {"type": "string"}, "city": {"type": "string"}, "state": {"type": "string"}, "zip_code": {"type": "string"}, "country": {"type": "string"}}, "required": ["street", "city", "country"]}, "transaction_fee": {"type": "number", "minimum": 0}, "external_transaction_ref": {"type": "string"}, "ip_address": {"type": "string", "format": "ipv4"}, "user_agent": {"type": "string"}, "gateway_name": {"type": "string"}}, "required": ["transaction_id", "order_id", "user_id", "amount", "currency", "status", "payment_method", "timestamp"]}',
        'Minor update: Added optional "gateway_name" field.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (4, 1, 5, 1,
        '{"type": "object", "properties": {"transaction_id": {"type": "string", "format": "uuid"}, "order_id": {"type": "string", "format": "uuid"}, "user_id": {"type": "string", "format": "uuid"}, "amount": {"type": "number", "minimum": 0, "exclusiveMinimum": 0}, "currency": {"type": "string", "pattern": "^[A-Z]{3}$"}, "status": {"type": "string", "enum": ["pending", "completed", "failed", "refunded", "disputed", "voided"]}, "payment_method": {"type": "string", "enum": ["credit_card", "paypal", "bank_transfer", "crypto"]}, "timestamp": {"type": "string", "format": "date-time"}, "processor_response_code": {"type": "string"}, "error_message": {"type": "string", "maxLength": 500}, "billing_address_snapshot": {"type": "object", "properties": {"street": {"type": "string"}, "city": {"type": "string"}, "state": {"type": "string"}, "zip_code": {"type": "string"}, "country": {"type": "string"}}, "required": ["street", "city", "country"]}, "transaction_fee": {"type": "number", "minimum": 0}, "external_transaction_ref": {"type": "string"}, "ip_address": {"type": "string", "format": "ipv4"}, "user_agent": {"type": "string"}, "gateway_name": {"type": "string"}, "metadata": {"type": "object", "additionalProperties": true}}, "required": ["transaction_id", "order_id", "user_id", "amount", "currency", "status", "payment_method", "timestamp"]}',
        'Patch: Added optional "metadata" object for flexible custom data.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (4, 1, 6, 0,
        '{"type": "object", "properties": {"transaction_id": {"type": "string", "format": "uuid"}, "order_id": {"type": "string", "format": "uuid"}, "user_id": {"type": "string", "format": "uuid"}, "amount": {"type": "number", "minimum": 0, "exclusiveMinimum": 0}, "currency": {"type": "string", "pattern": "^[A-Z]{3}$"}, "status": {"type": "string", "enum": ["pending", "completed", "failed", "refunded", "disputed", "voided", "authorized"]}, "payment_method": {"type": "string", "enum": ["credit_card", "paypal", "bank_transfer", "crypto"]}, "timestamp": {"type": "string", "format": "date-time"}, "processor_response_code": {"type": "string"}, "error_message": {"type": "string", "maxLength": 500}, "billing_address_snapshot": {"type": "object", "properties": {"street": {"type": "string"}, "city": {"type": "string"}, "state": {"type": "string"}, "zip_code": {"type": "string"}, "country": {"type": "string"}}, "required": ["street", "city", "country"]}, "transaction_fee": {"type": "number", "minimum": 0}, "external_transaction_ref": {"type": "string"}, "ip_address": {"type": "string", "format": "ipv4"}, "user_agent": {"type": "string"}, "gateway_name": {"type": "string"}, "metadata": {"type": "object", "additionalProperties": true}}, "required": ["transaction_id", "order_id", "user_id", "amount", "currency", "status", "payment_method", "timestamp"]}',
        'Minor update: Added "authorized" status.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (4, 1, 6, 1,
        '{"type": "object", "properties": {"transaction_id": {"type": "string", "format": "uuid"}, "order_id": {"type": "string", "format": "uuid"}, "user_id": {"type": "string", "format": "uuid"}, "amount": {"type": "number", "minimum": 0, "exclusiveMinimum": 0}, "currency": {"type": "string", "pattern": "^[A-Z]{3}$"}, "status": {"type": "string", "enum": ["pending", "completed", "failed", "refunded", "disputed", "voided", "authorized"]}, "payment_method": {"type": "string", "enum": ["credit_card", "paypal", "bank_transfer", "crypto"]}, "timestamp": {"type": "string", "format": "date-time"}, "processor_response_code": {"type": "string"}, "error_message": {"type": "string", "maxLength": 500}, "billing_address_snapshot": {"type": "object", "properties": {"street": {"type": "string"}, "city": {"type": "string"}, "state": {"type": "string"}, "zip_code": {"type": "string"}, "country": {"type": "string"}}, "required": ["street", "city", "country"]}, "transaction_fee": {"type": "number", "minimum": 0}, "external_transaction_ref": {"type": "string"}, "ip_address": {"type": "string", "format": "ipv4"}, "user_agent": {"type": "string", "maxLength": 255}, "gateway_name": {"type": "string"}, "metadata": {"type": "object", "additionalProperties": true}}, "required": ["transaction_id", "order_id", "user_id", "amount", "currency", "status", "payment_method", "timestamp"]}',
        'Patch: Added maxLength to user_agent.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (4, 1, 7, 0,
        '{"type": "object", "properties": {"transaction_id": {"type": "string", "format": "uuid"}, "order_id": {"type": "string", "format": "uuid"}, "user_id": {"type": "string", "format": "uuid"}, "amount": {"type": "number", "minimum": 0, "exclusiveMinimum": 0}, "currency": {"type": "string", "pattern": "^[A-Z]{3}$"}, "status": {"type": "string", "enum": ["pending", "completed", "failed", "refunded", "disputed", "voided", "authorized"]}, "payment_method": {"type": "string", "enum": ["credit_card", "paypal", "bank_transfer", "crypto"]}, "timestamp": {"type": "string", "format": "date-time"}, "processor_response_code": {"type": "string"}, "error_message": {"type": "string", "maxLength": 500}, "billing_address_snapshot": {"type": "object", "properties": {"street": {"type": "string"}, "city": {"type": "string"}, "state": {"type": "string"}, "zip_code": {"type": "string"}, "country": {"type": "string"}}, "required": ["street", "city", "country"]}, "transaction_fee": {"type": "number", "minimum": 0}, "external_transaction_ref": {"type": "string"}, "ip_address": {"type": "string", "format": "ipv4"}, "user_agent": {"type": "string", "maxLength": 255}, "gateway_name": {"type": "string"}, "metadata": {"type": "object", "additionalProperties": true}, "is_test_transaction": {"type": "boolean", "default": false}}, "required": ["transaction_id", "order_id", "user_id", "amount", "currency", "status", "payment_method", "timestamp"]}',
        'Minor update: Added optional "is_test_transaction" boolean field.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (4, 1, 7, 1,
        '{"type": "object", "properties": {"transaction_id": {"type": "string", "format": "uuid"}, "order_id": {"type": "string", "format": "uuid"}, "user_id": {"type": "string", "format": "uuid"}, "amount": {"type": "number", "minimum": 0, "exclusiveMinimum": 0}, "currency": {"type": "string", "pattern": "^[A-Z]{3}$"}, "status": {"type": "string", "enum": ["pending", "completed", "failed", "refunded", "disputed", "voided", "authorized"]}, "payment_method": {"type": "string", "enum": ["credit_card", "paypal", "bank_transfer", "crypto"]}, "timestamp": {"type": "string", "format": "date-time"}, "processor_response_code": {"type": "string"}, "error_message": {"type": "string", "maxLength": 500}, "billing_address_snapshot": {"type": "object", "properties": {"street": {"type": "string"}, "city": {"type": "string"}, "state": {"type": "string"}, "zip_code": {"type": "string"}, "country": {"type": "string"}}, "required": ["street", "city", "country"]}, "transaction_fee": {"type": "number", "minimum": 0}, "external_transaction_ref": {"type": "string"}, "ip_address": {"type": "string", "format": "ipv4"}, "user_agent": {"type": "string", "maxLength": 255}, "gateway_name": {"type": "string"}, "metadata": {"type": "object", "additionalProperties": true}, "is_test_transaction": {"type": "boolean", "default": false}, "refund_id": {"type": "string", "format": "uuid", "description": "ID of the refund transaction if applicable"}}, "required": ["transaction_id", "order_id", "user_id", "amount", "currency", "status", "payment_method", "timestamp"]}',
        'Patch: Added optional "refund_id" to link to a refund transaction.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content, description)
VALUES (4, 1, 8, 0,
        '{"type": "object", "properties": {"transaction_id": {"type": "string", "format": "uuid"}, "order_id": {"type": "string", "format": "uuid"}, "user_id": {"type": "string", "format": "uuid"}, "amount": {"type": "number", "minimum": 0, "exclusiveMinimum": 0}, "currency": {"type": "string", "pattern": "^[A-Z]{3}$"}, "status": {"type": "string", "enum": ["pending", "completed", "failed", "refunded", "disputed", "voided", "authorized"]}, "payment_method": {"type": "string", "enum": ["credit_card", "paypal", "bank_transfer", "crypto"]}, "timestamp": {"type": "string", "format": "date-time"}, "processor_response_code": {"type": "string"}, "error_message": {"type": "string", "maxLength": 500}, "billing_address_snapshot": {"type": "object", "properties": {"street": {"type": "string"}, "city": {"type": "string"}, "state": {"type": "string"}, "zip_code": {"type": "string"}, "country": {"type": "string"}}, "required": ["street", "city", "country"]}, "transaction_fee": {"type": "number", "minimum": 0}, "external_transaction_ref": {"type": "string"}, "ip_address": {"type": "string", "format": "ipv4"}, "user_agent": {"type": "string", "maxLength": 255}, "gateway_name": {"type": "string"}, "metadata": {"type": "object", "additionalProperties": true}, "is_test_transaction": {"type": "boolean", "default": false}, "refund_id": {"type": "string", "format": "uuid", "description": "ID of the refund transaction if applicable"}, "last_updated_at": {"type": "string", "format": "date-time"}}, "required": ["transaction_id", "order_id", "user_id", "amount", "currency", "status", "payment_method", "timestamp"]}',
        'Minor update: Added "last_updated_at" timestamp.');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content)
VALUES (5, 1, 0, 0,
        '{"type": "object", "properties": {"log_id": {"type": "string", "format": "uuid"}, "timestamp": {"type": "string", "format": "date-time"}, "level": {"type": "string", "enum": ["INFO", "WARN", "ERROR", "DEBUG"]}, "message": {"type": "string", "maxLength": 1024}}, "required": ["log_id", "timestamp", "level", "message"]}');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content)
VALUES (5, 1, 0, 1,
        '{"type": "object", "properties": {"log_id": {"type": "string", "format": "uuid"}, "timestamp": {"type": "string", "format": "date-time"}, "level": {"type": "string", "enum": ["INFO", "WARN", "ERROR", "DEBUG"]}, "message": {"type": "string", "maxLength": 1024}, "service_name": {"type": "string"}}, "required": ["log_id", "timestamp", "level", "message"]}');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content)
VALUES (5, 1, 1, 0,
        '{"type": "object", "properties": {"log_id": {"type": "string", "format": "uuid"}, "timestamp": {"type": "string", "format": "date-time"}, "level": {"type": "string", "enum": ["INFO", "WARN", "ERROR", "DEBUG", "CRITICAL"]}, "message": {"type": "string", "maxLength": 1024}, "service_name": {"type": "string"}, "correlation_id": {"type": "string", "format": "uuid"}}, "required": ["log_id", "timestamp", "level", "message"]}');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content)
VALUES (5, 1, 1, 1,
        '{"type": "object", "properties": {"log_id": {"type": "string", "format": "uuid"}, "timestamp": {"type": "string", "format": "date-time"}, "level": {"type": "string", "enum": ["INFO", "WARN", "ERROR", "DEBUG", "CRITICAL"]}, "message": {"type": "string", "maxLength": 1024}, "service_name": {"type": "string"}, "correlation_id": {"type": "string", "format": "uuid"}, "user_id": {"type": "string", "format": "uuid"}}, "required": ["log_id", "timestamp", "level", "message"]}');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content)
VALUES (5, 2, 0, 0,
        '{"type": "object", "properties": {"event_uuid": {"type": "string", "format": "uuid"}, "event_timestamp": {"type": "string", "format": "date-time"}, "severity_level": {"type": "string", "enum": ["INFO", "WARN", "ERROR", "DEBUG", "CRITICAL"]}, "event_description": {"type": "string", "maxLength": 2048}, "application_name": {"type": "string"}, "trace_id": {"type": "string", "format": "uuid"}, "actor_uuid": {"type": "string", "format": "uuid"}, "context_data": {"type": "object", "additionalProperties": true}}, "required": ["event_uuid", "event_timestamp", "severity_level", "event_description"]}');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content)
VALUES (6, 1, 0, 0,
        '{"type": "object", "properties": {"feedback_id": {"type": "string", "format": "uuid"}, "customer_id": {"type": "string", "format": "uuid"}, "rating": {"type": "integer", "minimum": 1, "maximum": 5}, "comment": {"type": "string", "maxLength": 2000}, "submission_date": {"type": "string", "format": "date"}}, "required": ["feedback_id", "customer_id", "rating", "submission_date"]}');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content)
VALUES (6, 1, 0, 1,
        '{"type": "object", "properties": {"feedback_id": {"type": "string", "format": "uuid"}, "customer_id": {"type": "string", "format": "uuid"}, "rating": {"type": "integer", "minimum": 1, "maximum": 5}, "comment": {"type": "string", "maxLength": 2000}, "submission_date": {"type": "string", "format": "date"}, "product_id": {"type": "string", "format": "uuid"}}, "required": ["feedback_id", "customer_id", "rating", "submission_date"]}');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content)
VALUES (6, 1, 1, 0,
        '{"type": "object", "properties": {"feedback_id": {"type": "string", "format": "uuid"}, "customer_id": {"type": "string", "format": "uuid"}, "rating": {"type": "integer", "minimum": 1, "maximum": 5}, "comment": {"type": "string", "maxLength": 2000}, "submission_date": {"type": "string", "format": "date"}, "product_id": {"type": "string", "format": "uuid"}, "feedback_type": {"type": "string", "enum": ["BUG", "FEATURE_REQUEST", "GENERAL_COMMENT", "COMPLAINT"]}}, "required": ["feedback_id", "customer_id", "rating", "submission_date"]}');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content)
VALUES (6, 1, 1, 1,
        '{"type": "object", "properties": {"feedback_id": {"type": "string", "format": "uuid"}, "customer_id": {"type": "string", "format": "uuid"}, "rating": {"type": "integer", "minimum": 1, "maximum": 5}, "comment": {"type": "string", "maxLength": 2000}, "submission_date": {"type": "string", "format": "date"}, "product_id": {"type": "string", "format": "uuid"}, "feedback_type": {"type": "string", "enum": ["BUG", "FEATURE_REQUEST", "GENERAL_COMMENT", "COMPLAINT"]}, "contact_email": {"type": "string", "format": "email"}}, "required": ["feedback_id", "customer_id", "rating", "submission_date"]}');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content)
VALUES (6, 2, 0, 0,
        '{"type": "object", "properties": {"feedback_record_uuid": {"type": "string", "format": "uuid"}, "user_uuid": {"type": "string", "format": "uuid"}, "score": {"type": "number", "minimum": 0, "maximum": 5}, "detailed_feedback": {"type": "string", "maxLength": 4000}, "recorded_datetime": {"type": "string", "format": "date-time"}, "item_uuid": {"type": "string", "format": "uuid"}, "category": {"type": "string", "enum": ["REPORT", "SUGGESTION", "REVIEW", "ISSUE"]}, "response_required": {"type": "boolean", "default": false}}, "required": ["feedback_record_uuid", "user_uuid", "score", "recorded_datetime", "category"]}');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content)
VALUES (7, 1, 0, 0,
        '{"type": "object", "properties": {"device_id": {"type": "string"}, "timestamp": {"type": "string", "format": "date-time"}, "temperature_c": {"type": "number"}, "battery_level_percent": {"type": "integer", "minimum": 0, "maximum": 100}}, "required": ["device_id", "timestamp", "temperature_c", "battery_level_percent"]}');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content)
VALUES (7, 1, 0, 1,
        '{"type": "object", "properties": {"device_id": {"type": "string"}, "timestamp": {"type": "string", "format": "date-time"}, "temperature_c": {"type": "number"}, "battery_level_percent": {"type": "integer", "minimum": 0, "maximum": 100}, "location_lat": {"type": "number"}, "location_lon": {"type": "number"}}, "required": ["device_id", "timestamp", "temperature_c", "battery_level_percent"]}');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content)
VALUES (7, 1, 1, 0,
        '{"type": "object", "properties": {"device_id": {"type": "string"}, "timestamp": {"type": "string", "format": "date-time"}, "temperature_c": {"type": "number"}, "battery_level_percent": {"type": "integer", "minimum": 0, "maximum": 100}, "location_lat": {"type": "number"}, "location_lon": {"type": "number"}, "network_strength_dbm": {"type": "integer"}}, "required": ["device_id", "timestamp", "temperature_c", "battery_level_percent"]}');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content)
VALUES (7, 1, 1, 1,
        '{"type": "object", "properties": {"device_id": {"type": "string"}, "timestamp": {"type": "string", "format": "date-time"}, "temperature_c": {"type": "number"}, "battery_level_percent": {"type": "integer", "minimum": 0, "maximum": 100}, "location_lat": {"type": "number"}, "location_lon": {"type": "number"}, "network_strength_dbm": {"type": "integer"}, "firmware_version": {"type": "string"}}, "required": ["device_id", "timestamp", "temperature_c", "battery_level_percent"]}');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content)
VALUES (7, 2, 0, 0,
        '{"type": "object", "properties": {"sensor_uuid": {"type": "string"}, "reading_timestamp": {"type": "string", "format": "date-time"}, "ambient_temp_c": {"type": "number"}, "power_percentage": {"type": "integer", "minimum": 0, "maximum": 100}, "gps_latitude": {"type": "number"}, "gps_longitude": {"type": "number"}, "signal_strength_db": {"type": "integer"}, "software_version": {"type": "string"}, "sensor_type": {"type": "string", "enum": ["TEMPERATURE", "HUMIDITY", "PRESSURE", "ACCELEROMOMETER"]}}, "required": ["sensor_uuid", "reading_timestamp", "ambient_temp_c", "power_percentage"]}');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content)
VALUES (8, 1, 0, 0,
        '{"type": "object", "properties": {"item_id": {"type": "string", "format": "uuid"}, "item_name": {"type": "string", "minLength": 3}, "quantity": {"type": "integer", "minimum": 0}, "warehouse_location": {"type": "string"}}, "required": ["item_id", "item_name", "quantity", "warehouse_location"]}');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content)
VALUES (8, 1, 0, 1,
        '{"type": "object", "properties": {"item_id": {"type": "string", "format": "uuid"}, "item_name": {"type": "string", "minLength": 3}, "quantity": {"type": "integer", "minimum": 0}, "warehouse_location": {"type": "string"}, "last_restock_date": {"type": "string", "format": "date"}}, "required": ["item_id", "item_name", "quantity", "warehouse_location"]}');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content)
VALUES (8, 1, 1, 0,
        '{"type": "object", "properties": {"item_id": {"type": "string", "format": "uuid"}, "item_name": {"type": "string", "minLength": 3}, "quantity": {"type": "integer", "minimum": 0}, "warehouse_location": {"type": "string"}, "last_restock_date": {"type": "string", "format": "date"}, "category": {"type": "string", "enum": ["Electronics", "Food", "Apparel", "Tools"]}}, "required": ["item_id", "item_name", "quantity", "warehouse_location"]}');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content)
VALUES (8, 1, 1, 1,
        '{"type": "object", "properties": {"item_id": {"type": "string", "format": "uuid"}, "item_name": {"type": "string", "minLength": 3}, "quantity": {"type": "integer", "minimum": 0}, "warehouse_location": {"type": "string"}, "last_restock_date": {"type": "string", "format": "date"}, "category": {"type": "string", "enum": ["Electronics", "Food", "Apparel", "Tools"]}, "supplier_id": {"type": "string"}}, "required": ["item_id", "item_name", "quantity", "warehouse_location"]}');
INSERT INTO json_schema_version (json_schema_id, version_major, version_minor, version_patch, content)
VALUES (8, 2, 0, 0,
        '{"type": "object", "properties": {"product_sku": {"type": "string"}, "product_description": {"type": "string", "minLength": 5}, "current_stock_level": {"type": "integer", "minimum": 0}, "storage_facility_code": {"type": "string"}, "last_received_shipment": {"type": "string", "format": "date"}, "product_category": {"type": "string", "enum": ["ELECTRONICS", "FOOD_BEVERAGE", "APPAREL_ACCESSORIES", "HOME_GOODS", "TOOLS_HARDWARE"]}, "vendor_uuid": {"type": "string", "format": "uuid"}, "reorder_point": {"type": "integer", "minimum": 0}}, "required": ["product_sku", "product_description", "current_stock_level", "storage_facility_code", "product_category"]}');
