openapi: 3.0.0
info:
  title: SchemaNest
  description: API Definition for SchemaNest
  version: 0.0.1
  contact:
    name: Timo Reymann
    url: https://timo-reymann.de
paths:
  /api/schema/json-schema:
    get:
      summary: List all available JSON schemas
      operationId: listJSONSchemas
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JsonSchemaVersions"
  /api/schema/json-schema/{identifier}:
    get:
      summary: Get versions of a json schema
      parameters:
        - in: path
          name: identifier
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Version JSON Schema"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JsonSchemaList"
        '404':
          description: "JSON Schema with identifier not found"
  /api/schema/json-schema/{identifier}/latest:
    get:
      summary: Get latest version of a JSON schema
      parameters:
        - in: path
          name: identifier
          schema:
            type: string
          required: true
      responses:
        '200':
          description: "Latest JSON Schema definition"
          content:
            application/json:
              schema:
                type: object
        '404':
          description: "JSON Schema with identifier not found"
  /api/schema/json-schema/{identifier}/channel/{channel}:
    get:
      summary: Get latest version of a JSON schema for a channel
      parameters:
        - in: path
          name: identifier
          schema:
            type: string
          required: true
        - in: path
          name: channel
          schema:
            type: string
          required: true
      responses:
        '200':
          description: "Latest JSON Schema definition"
          content:
            application/json:
              schema:
                type: object
        '404':
          description: "JSON Schema with identifier not found"
  /api/schema/json-schema/{identifier}/version/{version}:
    get:
      summary: Get latest version of a JSON schema
      parameters:
        - in: path
          name: identifier
          schema:
            type: string
          required: true
        - in: path
          name: version
          schema:
            type: string
          required: true
      responses:
        '200':
          description: "Latest JSON Schema definition"
          content:
            application/json:
              schema:
                type: object
        '404':
          description: "JSON Schema with identifier not found"
    post:
      summary: Create a new json schema for a version
      parameters:
        - in: path
          name: identifier
          schema:
            type: string
          required: true
        - in: path
          name: version
          schema:
            type: string
          required: true
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        '201':
          description: Created JSON Schema version"
        '409':
          description: Schema already was uploaded
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    JsonSchemaInfo:
      type: object
      required:
        - identifier
        - latestVersion
      properties:
        identifier:
          type: string
        latestVersion:
          type: object
          required:
            - major
            - minor
            - patch
          properties:
            major:
              type: integer
            minor:
              type: integer
            patch:
              type: integer
    JsonSchemaList:
      type: array
      items:
        $ref: "#/components/schemas/JsonSchemaInfo"
    JsonSchemaVersion:
      type: object
      additionalProperties: false
      required:
        - version
      properties:
        version:
          type: string
    JsonSchemaVersions:
      type: array
      items:
        $ref: "#/components/schemas/JsonSchemaVersion"
    Error:
      type: object
      additionalProperties: false
      required:
        - error
      properties:
        error:
          type: string
          description: Error message
