version: '2.1'

job_defaults: &job_defaults
  filters:
    tags:
      only: /.*/

orbs:
  github-cli: circleci/github-cli@2.7.0
  docker: circleci/docker@2.8.2
  codecov: codecov/codecov@5.3.0
  go: circleci/go@3.0.2

executors:
  go:
    docker:
      - image: cimg/go:1.24

jobs:
  test:
    executor: go
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - go/with-cache:
          steps:
            - run:
                name: Run tests
                command: |
                  gotestsum --junitfile unit-tests.xml
            - run:
                name: Get test coverage
                command:
                  go test -coverprofile=coverage.txt -covermode=atomic  -v ./...
      - codecov/upload
      - store_test_results:
          path: unit-tests.xml
      - store_artifacts:
          path: unit-tests.xml
      - store_artifacts:
          path: coverage.html
  build:
    executor: go
    steps:
      - checkout
      - go/with-cache:
          steps:
            - run:
                name: Build binaries
                command: make build -j3
      - persist_to_workspace:
          root: ./
          paths:
            - dist/

workflows:
  version: 2
  build:
    jobs:
      - test:
          <<: *job_defaults

      - build:
          <<: *job_defaults
          requires:
            - test
