version: '2.1'

job_defaults: &job_defaults
  filters:
    tags:
      only: /.*/

orbs:
  github-cli: circleci/github-cli@2.7.0
  docker: circleci/docker@2.8.2
  codecov: codecov/codecov@5.4.3
  go: circleci/go@3.0.2
  github-utils: trustedshops-public/github-utils@1.1.3
  node: circleci/node@7.1.0

executors:
  go:
    docker:
      - image: cimg/go:1.24
  node:
    docker:
      - image: cimg/node:lts

jobs:
  test:
    executor: go
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - go/with-cache:
          steps:
            - run:
                name: Run tests
                command: |
                  gotestsum --junitfile junit.xml -- -race -coverprofile=coverage.txt -covermode=atomic -v ./...
      - codecov/upload
      - store_test_results:
          path: junit.xml
      - store_artifacts:
          path: junit.xml
      - store_artifacts:
          path: coverage.txt
  build:
    executor: go
    steps:
      - checkout
      - go/with-cache:
          steps:
            - run:
                name: Build binaries
                command: make build -j3
      - persist_to_workspace:
          root: ./
          paths:
            - dist/
  build-ui:
    executor: node
    steps:
      - checkout
      - node/install-packages:
          app-dir: pkg/ui/nextjs
          pkg-manager: yarn-berry
      - run:
          name: Build frontend
          command: |
            cd pkg/ui/nextjs
            yarn build
      - store_artifacts:
          path: pkg/ui/nextjs/build
  build-gh-pages:
    executor: node
    steps:
      - checkout
      - run:
          name: Create gh-pages folder
          command: |
            mkdir -p gh-pages
      - run:
          name: Render api docs
          command: |
            npx -y @redocly/cli@1.34 build-docs openapi.yml --output gh-pages/apidocs.html
      - github-utils/publish_github_pages:
          folder: gh-pages/
          git_commit_author_email: "no-reply@timo-reymann.de"
          git_commit_author_name: "CircleCI"

workflows:
  version: 2
  build:
    jobs:
      - build-gh-pages:
          filters:
            branches:
              only: main
      - test:
          <<: *job_defaults
      - build-ui:
          <<: *job_defaults
      - build:
          <<: *job_defaults
          requires:
            - test
            - build-ui
